### ISSUE TITLE
Fix formatter indendation

### ISSUE THREAD

**Issue by robocoder** [scssphp/scssphp#1]
Copied from: https://github.com/leafo/scssphp/issues/291

* Fix indentation for @content, see @content tests

Clarification : this issue is about indentation differences (vs the reference ruby implementation) when using the Nested formatter.

Hint: see adjustAllChildren()

Nice-to-have: eliminate the separate adjustAllChildren() pass

**Comment by Cerdic** [comment]
@robocoder I just pushed a working branch with a refactoring of the Nested formatter that seems to solve a lot of cases in the ruby test cases.

https://github.com/scssphp/scssphp/commits/dev/formatter-nested

This a somme little impacts on outputs test, and a lot on outputs_numbered because having a blank line before each numbering comment line.
I let you have a look and tell me if you think it's close enough from the ruby implementation.

I got rid of the `adjustAllChildren()` and did all the work in the `block()` function but I don't know if it's really better understandable, because a little tricky at the end - at least it should be faster and less memory consuming.

Some cases are still not good like https://github.com/scssphp/scssphp/blob/master/tests/scss_test.rb#L802 but the Formatter alone can't do anything here as lines are coming all-in-one formatted from the Compiler. This case will need some improvement in the Compiler itself

**Comment by robocoder** [comment]
Compatibility improved. Looks good to merge.

**Comment by Cerdic** [comment]
This is now in the master branch (with some commits rewriting/cleaning)

**Comment by Cerdic** [comment]
I think we can close this now :)
