### ISSUE TITLE
[RFC] use an uptodate version of sass-spec for the testsuite

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#152]
Currently, we use the libsass-3.6.0 tag of the sass-spec repository, which is 330 commits behind master as of today.

I tried updated sass-spec to https://github.com/sass/sass-spec/commit/73222792c42a516d62e2e25c3f5d9e35f5567030 (which is currently the master branch). And SassSpecTest runs a lot more tests:

- before: Tests: 1981, Skipped: 728  -> 1253 executed specs (which are passing)
- after: Tests: 3971, Skipped: 1544  -> 2427 executed specs (which are passing)

As we already have the infrastructure in place to manage skipping specs that are not supported, I suggest that we run an uptodate version of sass-spec rather than a version from 1 year ago, to benefit from all the new tests added in the meantime.
what do you think ?

**Comment by stof** [comment]
Note that among the new skipped specs, a bunch of them are about cases where the code has bugs, trying to call methods on `null` for instance. Working on them might actually improve the error handling for invalid Sass files a lot.

**Comment by Cerdic** [comment]
Problem is that after libass-3.6.0 tag the spec includes the modules and with that comes all the new syntaxes on functions with the `.` instead of the `-`

I don't think this is helping to have a moving reference as a spec, including a lot of stuff we know we are not going to be able to reach at a short term.

Based on libsass-3.6.0 we at least have a clear target, that should be the zero skipped tests - excepted maybe some that we are going to exclude manually for a clear reason

Based on the master spec, we know that a lot of tests are not going to be reachable without a massive refactoring, which is another direction. Then you have to pick in the 1500 something skipped test and sort them to be able to say which one you should fullfill and which one not. This process could involve a lot of time spent and lost on issues that are not reachable.

I would rather prefer to keep the 3.6.0 as a clear milestone before trying to reach a more ambitious target.

But what we could do is to add an extra test section, working the same way but based on the autoupdated master, to benefit of the larger test base, using it as a non regression test base (ie this test serie would be helpfull when we are trying to fix a bug to ensure we are not breaking something)

**Comment by stof** [comment]
> Problem is that after libass-3.6.0 tag the spec includes the modules and with that comes all the new syntaxes on functions with the `.` instead of the `-`

most of the specs are not using the module syntax, as they don't need to deal with multiple modules. The only hrx files using `@use` or `@forward` (the module API) are in these folders:

- `directives/forward`
- `directives/use`
- `core_functions/modules` (this contains the test for the built-in modules API, while the equivalent API exposed through global functions are covered by other files in `core_functions`)
- `core_functions/meta` for some of the specs inside it (logical, because meta functions have features to check whether a function exists in a used module, for instance)
- `core_functions/math` for a few specs (some math functions are available only through the module API, without a global alias, as they are new)

Everything else in sass-spec does not depend on modules.

What I could do is split out the tests involving `@use` or `@forward` into a separate exclude list file, which gets always skipped even when passing `TEST_SASS_SPEC=1`, so they don't both us until we start working on modules. That should be easy to do by matching `@use` and `@forward` in the `input.scss`.
but this will still help with the hundreds of other tests which actually cover cases that belong to code we already have (many of them being about handling edge cases to report proper errors, which is good to do).

**Comment by stof** [comment]
Among the 1544 skipped tests in the latest sass-spec, only 248 are related to modules.
