### ISSUE TITLE
1.2 breaking change

### ISSUE THREAD

**Issue by JeroenDeDauw** [scssphp/scssphp#170]
I maintain a popular MediaWiki skin called Chameleon (https://github.com/ProfessionalWiki/chameleon).

Going from 1.1.1 to 1.2 of this library breaks the skin. I found by accident that this is caused by the recent scssphp/scssphp release, after spending several hours on this issue. I still do not know what is failing, the failure is silent. Will pin to 1.1.1 for now as I do not have more time to look at this.

I know this is not a proper report but wanted to give you a heads up

**Comment by Cerdic** [comment]
Indeed this is not a super helping report :)

Sorry for the inconvenience, indeed some breaking bugs have been reported since the release of the 1.2, mainly due to a big refactoring, and despite a much larger test base.

All the reports have been fixed in the master.

So maybe you can try compiling with the master and give us a feedback if it's solving your issue also or not at all?
This would be a good help for us to know if we should release a 1.2.1 or still search for other broken features.

**Comment by JeroenDeDauw** [comment]
Found the error, apparently the silencing was happening somewhere in the MW stack.

> @return may only be used within a function: /home/travis/build/ProfessionalWiki/mw/skins/chameleon/resources/styles/_functions.scss on line 22, at column 4

Relevant SCSS: https://github.com/ProfessionalWiki/chameleon/blob/master/resources/styles/_functions.scss#L22

**Comment by Cerdic** [comment]
@JeroenDeDauw there is good chance it is the same issue as #168 caused by a bug in the parsing of the `@if` statement.

This has been fix in the master

**Comment by JeroenDeDauw** [comment]
Then a new release would be super ;)

**Comment by Cerdic** [comment]
Indeed (ping @robocoder if you have some time for a release)

**Comment by robocoder** [comment]
Sure. I'll get a new release out.
