### ISSUE TITLE
Problem with comments that misassemble the code

### ISSUE THREAD

**Issue by Daijobou** [scssphp/scssphp#175]
I use scsssphp 1.2.1 with this code

I have this code and the first line is the problem

```
#instagram, #facebook/*, #google*/ {
	&:before {
		font-family: 'FontAwesome';
	}
}
#instagram {
	&:before {
		content: "\f16d";
	}
}
#facebook {
	&:before {
		content: "\f230";
	}
}
```
After compiling with `$scss->setFormatter('ScssPhp\ScssPhp\Formatter\Crunched');` result is that only #facebook have lost first block with `font-family: 'FontAwesome';` because the comment. Remove comment or add a single space between #facebook and comment and its working fine.

Maybe a bug you don't have to fix, but at least I wanted to mention it. ;)

**Comment by Cerdic** [comment]
This is indeed a bug: 

```
#instagram, #facebook/*, #google*/ {
	&:before {
		font-family: 'FontAwesome';
	}
}
```

compiles nicely in the following with sassmeister: 

```
#instagram:before, #facebook:before {
  font-family: "FontAwesome";
}
```

but not with scssphp:
```
#instagram:before, #facebook /*, #google*/:before {
  font-family: 'FontAwesome'; }
```

**Comment by Cerdic** [comment]
Hey @robocoder this bug is coming from the line
https://github.com/scssphp/scssphp/blob/master/src/Parser.php#L3390

which is only useful for handling this selector
https://github.com/scssphp/scssphp/blame/master/tests/inputs/selectors.scss#L88

But I cannot find any documentation about this CSS4 selector. I have the feeling it is coming from a past future specification.
Any opinion if we should keep this support, improving it to not eat a comment, or simply delete it?

FYI Sassmeister is refusing to handle this selector `E /foo/ F`  considering this is an error.

**Comment by Cerdic** [comment]
The bug is solved, the question about `/foo/` selector remains an open point
