### ISSUE TITLE
Extension needs for the SPIP extension

### ISSUE THREAD

**Issue by stof** [scssphp/scssphp#215]
The code for this extension (maintained by @Cerdic) is available at https://git.spip.net/spip-contrib-extensions/scssphp/ with the custom compiler being in https://git.spip.net/spip-contrib-extensions/scssphp/src/branch/master/inc/scssphp_compiler.php

Subclassing the Compiler is done only to add the `find-in-path` function. Everything else is done using public APIs defined in #201 (mostly the customization of import paths).
However, I think that this `find-in-path` function cannot be migrated to use `registerFunction` right now due to the APIs used in its implementation:

- `$this->reduce()` is fine as it could be called as `$compiler->reduce()` if defined elsewhere (side note: this usage is useless. When functions are called, their arguments are already reduced by the compiler so this call is a no-op)
- `$this->compileValue` is fine as it could be called as `$compiler->compileValue()` if defined elsewhere.
- The issue is accessing `$this->sourceNames`

@Cerdic can you give more details about the use case for reading `$this->sourceNames` in this function ? According to a comment, the goal is to find the path of the main scss file (the one from which the compilation started). But I don't know why there is such a need.
And for reference, I can tell for sure that the dart-sass API for custom functions does not grant access to such info.

**Comment by Cerdic** [comment]
this function has two distinct purposes:

1. allow to find images (or sometimes fonts) in the path dirs
Thus it allows the user/webmaster/another plugin/whoever to overwrite it by adding a new image in it's personalization folder/a folder from the path that will then overwite the default image

2. deal with the mess in images and fonts path in scss compilation when you are compiling a scss importing files from directories from the path ie not directly related to the directory of the main scss file.
* At the end, the scss compiler produce a css file, in which all `url(...)` are expected to be relative URL to the CSS url
* as we are using static files and by default no rewriteRules, urls are linked to the path
* the final css path is expected to be the same as the main scss file compiled
* any `url(...)` that appears in the scss compilation is untouched, and that means that the path you have to provide in the `url(...)` itself has to be relative to the final css path aka the main scss file compiled whatever is the path of the `@import` you are compiling.

so this function has to resolve the path of the image/font it founds and make it relative to the initial scss file.

To be complete, after the compilation, the css itself is postprocessed to translate all relatives urls in absolute urls
https://git.spip.net/spip-contrib-extensions/scssphp/src/branch/master/scssphp_fonctions.php#L153

So I guess I could have alternatives options like
- provide absolute urls directly in the result of `find-in-path()` function - but then it would make the result of the scss compilation dependent from the url of the main scss, which is not the case now (ie even if the website is serving several domains, right now it doesnt needs to compile the scss for each domain) 
- provide absolute path out of `find-in-path()` function and translate it afterwards to absolute URLs - but this is not consistent and also make the result dependant from the file path on the server

Right now I'm using `$this->sourceNames` to get the path of the main scss file, because it was available as a method, but I could also use a registered function, which I would provide with the main scss path before starting the compilation - as I know what I'm going to Compile.

So I think this should not be a blocking point for scssphp evolution

**Comment by stof** [comment]
> but I could also use a registered function, which I would provide with the main scss path before starting the compilation - as I know what I'm going to Compile.
> 
> So I think this should not be a blocking point for scssphp evolution

that's a great news.

So I'm closing this issue as there is no blocker.
