### ISSUE TITLE
src/Version.php

### ISSUE THREAD

**Issue by robocoder** [scssphp/scssphp#262]
I've overlooked bumping the version number in this file in the past after tagging the branch for a release.

Should we eliminate it? Or add a test for consistency? Or perhaps add a script that both updates etc/Version.php and tags the branch (eg customize https://github.com/pnikosis/semtag).

**Comment by stof** [comment]
Eliminating it would make it harder for projects not using composer (composer has APIs to get the version number).

Also, I think a proper cache API (see #237) should use the version number as cache busting (instead of a separate cache version which is never updated).

> Or add a test for consistency

I don't think that will help. If tests fail on the tag, that's already too late.

**Comment by stof** [comment]
The documentation for the release process (see #313) should help here.

**Comment by stof** [comment]
I'm closing this as our cache implementation uses it as cache busting, so we cannot eliminate the class (and we cannot require being in a Composer 2 environment where we have a composer API for that).
I hope that the documented process helps here.
