### ISSUE TITLE
v1.4 highly breaks the import behavior

### ISSUE THREAD

**Issue by gilbertsoft** [scssphp/scssphp#271]
The commit https://github.com/scssphp/scssphp/commit/e525b857a7487ee8a14b452e5addbdb4c69a390f is highly breaking for us in the [Bootstrap Package](https://github.com/benjaminkott/bootstrap_package). All our functional tests are failing after this commit and users are complaining about a broken Bootstrap Package since version 1.4.

See also https://github.com/benjaminkott/bootstrap_package/issues/947

For the moment I do not have more details but I will add it here if I find something useful.

**Comment by stof** [comment]
Please provide a reproducing case. Just saying `it's broken` without further info about which error you get and how to reproduce it does not allow us to do anything.

**Comment by gilbertsoft** [comment]
Yeah, I'm on it. It really complicated use case with symlinks, will take a while...

**Comment by gilbertsoft** [comment]
As far as I can see the import path functions now receiving always an absolute path which breaks our implementation. Checking for an absolute path fixes our implementation see https://github.com/benjaminkott/bootstrap_package/pull/948/files.

Feel free to close this issue.

**Comment by mahagr** [comment]
I'm actually already discussing imports using `realname()` in multiple issues. There are already few proposals and thoughts how to make library more general.

**Comment by stof** [comment]
> As far as I can see the import path functions now receiving always an absolute path which breaks our implementation.

that's weird to me. As far as I can tell, the callable importer receives exactly what you have in your scss file in `@import`, and that was also the case before my refactoring.

**Comment by markusmilkereit** [comment]
I can second the broken behaviour for the Contao CMS, the relative paths in the `@include` statement get translated to absolute paths in a wrong way. I would guess that the base directory is off. After updating an installation we also got version 1.4 of scssphp and the includes where all broken.

**Comment by stof** [comment]
@markusmilkereit are you passing the path to your entrypoint file to the `compile()` method (as the second argument) when compiling content coming from a file ?

**Comment by markusmilkereit** [comment]
The Contao CMS is using the compiler like this: 
```PHP
$objCompiler = new Compiler();
$objCompiler->setImportPaths($this->strRootDir . '/' . \dirname($arrFile['name']));
$objCompiler->compile($content);
````
Which worked until 1.3 - I'm posting an update soon, I'm just installing the "broken" version again to see where the different handling is coming from.

**Comment by stof** [comment]
oh crap. The old behavior of `setImportPaths` removing the default resolution based on the current working directory, while I kept BC for the current directory resolution when omitting the path argument.

The clean way in your case to make relative imports be resolved properly is to pass the path of the source file as second argument to `compile` (probably `$objCompiler->compile($content, $this->strRootDir . '/' . $arrFile['name']);` in your case).
Note that if the import path you set is only meant to resolve relative imports for your initial content but not other imports, you might be able to remove that import path in 1.4 as relative imports are now properly resolved.

I'll look tomorrow into improving the code for backward compatibility in projects which used `setImportPaths` rather than `addImportPaths` and so removing the empty string from import paths.

**Comment by markusmilkereit** [comment]
The update I wanted to post is that the logic of `resolveImportPath` actually destroys relative paths, because you just add the basepath to the relative path - not the current path of the SCSS file (from which it is relative).

**Comment by stof** [comment]
@markusmilkereit not true, because `$this->currentDirectory` gets updated for each processed import.
The issue is only for the initial `compile()` call when not passing a path.

**Comment by stof** [comment]
@markusmilkereit can you try if #278 fixes the BC break ?

**Comment by axllent** [comment]
I am assuming this is directly related, however I'm experiencing breakage for any `@import` that uses an absolute path, eg:
`@import "/var/www/site/vendor/twbs/bootstrap/scss/alert";` ("file not found for..."). The files exist of course (`/var/www/site/vendor/twbs/bootstrap/scss/_alert.scss`), and it's always worked perfectly, but since v1.4 no absolute path works. Switching to relative paths fixes it, however I don't see that as a fix, more a band aid. The patch (#278) does not fix this either.
```
private function resolveImportPath($url, $baseDir)
    {
        $path = rtrim($baseDir, '/') . '/' . ltrim($url, '/');
```
`resolveImportPath()` appears to be the culprit, which transforms `/var/www/site/vendor/twbs/bootstrap/scss/alert` into `/var/www/site/themes/site/css/var/www/site/vendor/twbs/bootstrap/scss/alert`.

**Comment by qzminski** [comment]
I have the same problem as @axllent here. The absolute import paths no longer work as of version 1.4.

Furthermore, I find the `compile()` path handling a bit strange. The method in fact accepts the code (not the file!) that needs to be compiled, which means that the file doesn't have to exist. On the other hand, if the file does not exist, you cannot provide the directory to make the imports work correctly because it explicitly checks for a file (https://github.com/scssphp/scssphp/blob/master/src/Compiler.php#L378), but you should also be able to provide the directory name. Why is this important? The current directory is set using `$this->currentDirectory = getcwd();` which can lead to incorrect results as `getcwd()` may set the path inside `<project_dir>/web` folder instead of just `<project_dir>`. And I cannot pass the project directory as path because it's not an actual file 🤷🏻‍♂️

Or am I missing something here?

**Comment by stof** [comment]
The path is indeed expected to be an existing file. There is no support for fake files that you want to consider being part of a directory. That's consistent with the API of the official sass implementation.

If you want to allow imports relatively to another directory, that's what import paths are for.

**Comment by qzminski** [comment]
Thank you for the reply, that makes sense. What about the absolute paths, though? Why are they no longer working and is there any chance to bring back that functionality? See @axllent example, I've got pretty much identical case.

**Comment by stof** [comment]
the absolute paths not working anymore is a bug. that's on my TODO-list.
