### ISSUE TITLE
Compiling with OutputStyle::COMPRESSED. SourceMaps show wrong scss files and lines.

### ISSUE THREAD

**Issue by ReLater** [scssphp/scssphp#275]
- I'm compiling Bootstrap v4.5.3 plus some other scss files into a file `template.css`. (EDIT: I've also tested a blank Bootstrap package meanwhile.)
- When I use output style `OutputStyle::EXPANDED` the sourcemap files are OK and show me correct scss files and line numbers.
- When I use  `OutputStyle::COMPRESSED` the scss infos in browser inspector are complete nonsense. Wrong files, wrong line numbers.

- Current ScssPHP package included via composer.
- Current Firefox. Current Edge (chromium).
- Win10/64. Xampp 7.3.

**Comment by stof** [comment]
> * Current ScssPHP package included via composer.

please report the exact version (`composer show scssphp/scssphp` will give you the info).

**Comment by ReLater** [comment]
composer.lock says:
```
"source": {
	"type": "git",
	"url": "https://github.com/scssphp/scssphp.git",
	"reference": "f7c9088320e218ca42e4ef0074259a1ba24ec93a"
}
```
A bit irritating for me. `scssphp/src/Version.php` says:
```
class Version
{
	const VERSION = '1.3';
}
```
But I've compared the files yesterday with the last 1.4.0 release from this repository. No differences. Same files.

**Comment by ReLater** [comment]
Forgot to mention the version. Added in last comment.

**Comment by stof** [comment]
yeah, we forgot to update the `Version::VERSION` constant when preparing the 1.4.0 release.

**Comment by stof** [comment]
I found the issue. The 1.4.0 release has refactored the generation of sourcemaps to fix many issues with them. But a bug in the new code breaks things when multiple writes are concatenated in a single line of the output (which happens almost never in expanded mode, but happens for almost everything in compressed mode). The `currentColumn` was reset instead of being incremented in this case.
