### ISSUE TITLE
A few questions regarding the usage of SCSS

### ISSUE THREAD

**Issue by MikaReesu** [scssphp/scssphp#295]
Hello, 

I just started using SCSS and I need some information.

Is SCSS used only in inline or should it be used in the classic way :
`<link type="text/css"rel="stylesheet" href="style.css>">`
Loaded with a link. I'm not sure if I understand the SCSS properly at the moment, so that's why I am asking this weird question. 

If the usage is intended to be with a link, could please provide me an example, please? I find the documentation, not documented enough and more explanation on some aspect would be good.

In the case, if we load only all the css inline, will that be fine regarding the performances ?

Thank you for you kind answers :)

**Comment by stof** [comment]
Compiling the Sass source into CSS on each page rendering is probably a bad idea from a performance point of view. Compiling Sass to CSS takes time.

The Sass compilation generally happens during the deployment process (or even before that in case you commit the generated CSS alongside the source). Then, the generated CSS file is used normally.
If you need to support dynamic sources (in a CMS allowing the admin to write SCSS for instance), you should definitely implement some caching of the generated CSS, so that you regenerate it only when the source changes.

The way the CSS (inline or in an external file) is loaded does not matter for SCSS, because SCSS is only about generating the CSS, not about shipping it to browser.

**Comment by MikaReesu** [comment]
Thank you for your answer. So, is it used for a general css file or instead for one per page?

**Comment by stof** [comment]
you can do what you want. Sass is a compiler turning a SCSS file into a CSS file.
Having one general SCSS file or one specific SCSS file per page (and then compiling each of them to CSS with Sass) is your choice, depending on your needs.

**Comment by MikaReesu** [comment]
Is there any information in the doc or somewhere else to how to achieve a specific SCSS file per page ? 

Where in your opinion is it the best to do the compilation of the css ?

**Comment by stof** [comment]
Just call the compiler multiple times (once per file you want to compile). How you do it is out of scope of our doc, because it depends of where you use the compiler.

**Comment by MikaReesu** [comment]
Thank you, where do you usually compile it? In your normal usage.

**Comment by stof** [comment]
In my normal usage, I'm using the official sass implementation installed through the `sass` npm package and I'm using it in my gulp pipeline to build a few CSS files in my build pipeline (I don't have one CSS file per page, as that would be quite bad for caching during navigation, but I still do have a few CSS files for separate parts). This build runs during my deployment process (and I run it in watch mode locally)
I'm only using scssphp for a custom need where I need to compile some Sass file dynamically (and then I have a cache). But some CMS have plugins using scssphp to render custom styles configured by the admin, as described.
Note that the main use case for scssphp is probably for such integrations. For a build pipeline, it is often OK to rely on non-PHP tools, and then the official (faster) implementation should be used.

**Comment by MikaReesu** [comment]
I see, thank you very much for the help :). That is clearer for me!
