### ISSUE TITLE
Should ScssPhp provide the Cache mecanism?

### ISSUE THREAD

**Issue by Cerdic** [scssphp/scssphp#316]
Linked to https://github.com/scssphp/scssphp/pull/270#issuecomment-763503445 and https://github.com/scssphp/scssphp/pull/315#issuecomment-796802448

dart-sass is not offering any of this mecanism but is probaly fast enough in compilation time to avoid this need

scssphp is taking seconds to compile BootStrap and is not fast enough to be used in a CMS as a on the fly compilation tool without any cache.

So : or it has to provide it's own caching mecanism, or provide api point to allow the user to provide a cache mecanism.

ScssPhp is using two caching level right now : 
- one for the parsing
- one for the complete compilation result

Both are useful. With this, for instance, modifying just the `_variables.scss` in the BS compilation need only to reparse this file and compile the whole, and this is a real life situation : website development is mainly iterative with modifications on one or some scss files and checking the visual result.

A cache for the whole compiled result could be managed outside scssphp, as long as scssphp is returning enough information like the list of `@import` resolutions with the useful data to check the resolution is unchanged.

But a cache mecanism for the parsing needs a specific entry point for caching to allow the parser to rely on it.

For now the cache logic is provided by scssphp, but we could consider the user a to rely on an external cache tool IF scssphp is providing the right API for that...

**Comment by stof** [comment]
I tend to agree that compilation caching could be dropped and left to the caller. https://github.com/scssphp/scssphp/pull/315#issuecomment-796838327 exposes my idea for providing cache invalidation logic to the caller (which can then choose to use it or no)
The parsing cache is a lot simpler, as it does not require supporting any external implementation. It is about caching the result of parsing an input (with its hash used as cache key) with our own parser implementation (no extension point in it, so the parsing logic is entirely invalidated by a check on the Scssphp version).

Is this parsing cache necessary though ? When profiling a compilation of bootstrap, I get more than 80% of the time being spent in the compiler. The parser is not the bottleneck right now.

the `Scssphp\Scssphp\Cache` class is also awful right now:
- it is not customizable if you want to store the cache elsewhere than on the filesystem
- it has a weird design as it relies on an instance but stores all config in static properties, meaning you can only have one instance at a time

Proposal (assuming we want to keep parsing caching):

- implement the cache freshness API that I suggested in https://github.com/scssphp/scssphp/pull/315#issuecomment-796838327 (but including `Version::VERSION` in the cache info as well, to replace the fact that our `Cache` enforces it for now, or expecting embedded to include `Version::VERSION` in their cache key, to be decided)
- get rid of `Compiler::getCompileOptions` as cache busting things, as it has several issues (it relies on the config of the Compiler to be serializable, which will break if you pass a callable importer instead of a directory in `importPaths` for instance as that won' play well with `json_encode` or `serialize`):
    - modifying `registeredFeatures` is deprecated, so this is covered by the library version check
    - `importPaths` and `legacyImportPath` are config impacting the import resolution. If any changes in that config impacts the result, that's already covered by the import resolution check
    - other keys are about the config of the Compiler instance itself. To me, it would be fine to leave this to the embedder: if they dynamically alter the config of the compiler, they need to account for the relevant moving parts in their cache invalidation. But they can control that (and they can have more knowledge about what is moving and how to include that in the cache invalidation than our attempt to serialize the config in the cache key, which 
- support for passing a PSR-6 CachePool to store the parsing cache in the Compiler constructor, in place of the `$cacheOptions`:
    - if a CachePool is provided, compilation cache is disable. Only parsing cache happens.
    - if `null` is passed (or the argument is omitted as that's the default value), no caching happens (same than today)
    - if an array is passed, enable the legacy caching layer (both compilation and parsing) with `Scssphp\Scssphp\Cache` and trigger a deprecation warning
- deprecate the `Scssphp\Scssphp\Cache` class

Using PSR-6 for the parser cache allows embedders to customize where the cache is stored without having to maintain our own cache library (which is not in our scope).

**Comment by mahagr** [comment]
I tend to agree that the caching should be something that the application should handle -- for example application may know when the filesystem changes -- in production mode Gantry only checks the filesystem when something has been installed or updated. This helps to speed up the process as recompilation only needs to pass the dynamic variables and configuration changes.

That said, parse cache should not assume that the files are in the filesystem, either (some hosts make filesystem read-only and force to use a database instead), which is why there needs to be a way to way to hook custom method into file imports, too. Both of these can be handled at the application level as long as the library supports this.

**Comment by stof** [comment]
@mahagr the parse cache is not about loading files from the file system. It is about caching the result of parsing a string (containing SCSS source code) into our internal structure. The file name is only used as part of the cache key there.
Loading file content is done as part of our importer layer. Allowing more customization there is a separate topic.

**Comment by stof** [comment]
Note that I would be in favor of removing the persistent parsing cache as well if possible. I started experimenting with rewriting the parser as a port of the dart-sass one, producing a proper AST, including the source tracking with their FileSpan. But the result of that improved source tracking (which would give us much better error reporting and more precise source maps) is that serializing the AST is much less straightforward than serializing the existing crappy parser result.

**Comment by stof** [comment]
In #728, I'm dropping the cache system entirely as my previous intuition about being hard to implement in the new API ported from dart-sass was right.
