### ISSUE TITLE
browser could not read map

### ISSUE THREAD

**Issue by jafarghasemi** [scssphp/scssphp#35]
```php
include_once get_template_directory() . '/inc/class/scssphp/scss.inc.php';
use ScssPhp\ScssPhp\Compiler;


add_action( 'customize_save_after', function() {

    // get scss & css
    $scss = get_theme_mod( 'custom_scss',$GLOBALS['default_scss']);
    $css = wp_get_custom_css();

    // add scss+css to custom.scss file
    $scss_dir = trailingslashit( get_template_directory().'/assets/scss/' ); 
    $css_dir = trailingslashit( get_template_directory().'/assets/css/' ); 
    if (!file_exists($scss_dir)) mkdir($scss_dir, 0777, true);
    if (!file_exists($css_dir)) mkdir($css_dir, 0777, true);
    $scss_file = $scss_dir.'custom.scss';
    $css_file = $css_dir.'custom.css';
    $css_file_url = get_template_directory_uri().'/assets/css/custom.css';
    $map_file = $css_dir.'custom.css.map';
    $map_file_url = get_template_directory_uri().'/assets/css/custom.css.map';
    $content=$scss."\n". $css;
    file_put_contents($scss_file, $content);
    
    //compile scss 
    include_once get_template_directory() . '/inc/class/scssphp/scss.inc.php';
    $s = new Compiler();
    $s->setFormatter('ScssPhp\ScssPhp\Formatter\Crunched');
    $s->setSourceMap(Compiler::SOURCE_MAP_FILE);
    $s->setSourceMapOptions([
        // absolute path to write .map file
        'sourceMapWriteTo'  => $map_file,
    
        // relative or full url to the above .map file
        'sourceMapURL'      => $map_file_url,
    
        // (optional) relative or full url to the .css file
        'sourceMapFilename' => $css_file_url,
    
        // partial path (server root) removed (normalized) to create a relative url
        'sourceMapBasepath' => $css_dir,
    
        // (optional) prepended to 'source' field entries for relocating source files
        'sourceRoot'        => '/' ,
    ]);

    $s->setImportPaths(trailingslashit( get_template_directory().'/assets/bootstrap/scss/' ));
    $sOut = $s->compile($content);
    file_put_contents($css_file, $sOut);

} );
```

**Comment by jafarghasemi** [comment]
plead give information or working example about SourceMap

**Comment by robocoder** [comment]
* is the compiled .css generated correctly?
* does custom.scss have any other external requirements besides bootstrap? (just wondering why $scss_dir isn't included in your import path)
* is the source map file generated correctly?
* when you say the browser can't read it, have you tried entering the map file URL in the browser's address bar?

The end of the compiled css should contain something like:
`/*# sourceMappingURL=your_map_file_url */`

**Comment by iannacone** [comment]
actually i also have problem with the source map on firefox when the access is password protected (.htaccess + .htpasswd)

**Comment by benwallis** [comment]
I can't get source maps to work either.
sourceMappingURL looks correct

On my Windows machine, in the .mao file the sources are like:
"sources":["(stdin)","C:/www/jarbon/wp-content/themes/john-arbon-textilles/classes/../scss/bf/src/navigation.scss"

**Comment by stof** [comment]
@benwallis regard absolute paths in the sourcemap, configure the `sourceMapBasepath` and `sourceMapRootpath` options. These options configure the normalization of filenames in `sources`:
- `sourceMapBasepath` configures the base path to replace (for instance `C:/www/domain/wp-content/themes/theme-name/classes/../scss/` or `C:/www/domain/wp-content/` in your cases (notice that we have a weird thing where this options must use `/` instead of `\` on Windows)
- `sourceMapRootpath` configures the replacement value

And a separate `sourceRoot` option exists, which will be prepend *by the browser* when needing to load the file (so it could be used instead of `sourceMapRootpath` in most cases.

For development environment, you can also set the `outputSourceFiles` to `true` to embed the source content directly in the sourcemap (avoiding the need to load extra files altogether and so working even if your scss files are not accessible by the browser). But doing that in production would leak the original content of the files, so it might not be a good idea depending on what you have in it.

**Comment by mirateam** [comment]
`sourceMapWriteTo` - option is not working for me:

```
'sourceMapWriteTo'  => '/var/www/vhost/my-style.map'
```

...so I use `getSourceMap`:

```
file_put_contents('/var/www/vhost/my-style.map', $result->getSourceMap());
```

May I ask you, why some import files not appearing in the source map? For example I have vars.scss file that contain only variables: 

```
$color1: #ff0000;
$color2: #00ff00;
....
```

Compiler excludes this source-file from the MAP. Is it possible to include all import files in my MAP?

**Comment by stof** [comment]
@mirateam the `sourceMapWriteTo` option is part of the legacy API. It is not used by the new API, which does not write anything to the disk.

Regarding the included files, the source map only contains filenames that are referenced in the mapping, because others are useless in the source map. And scssphp only defines source maps at the rule level, so it does not care about variable declarations. Scssphp 2.0 will have more granular mappings, similar to those of dart-sass, but that still does not guarantee to have all imported files as that's not what source maps are about.
The `CompilationResult` exposes that list of included files though.

**Comment by stof** [comment]
Closing this as no feedback has been provided since *years* for the original issues (comments from 2 weeks ago are about a separate problem that high-jacked that issue instead of creating a new one).
