### ISSUE TITLE
v1.5.0 fails to compile bootstrap 5.0.1

### ISSUE THREAD

**Issue by axllent** [scssphp/scssphp#397]
I am getting the following error after upgrading to v1.5.0 when compiling bootstrap 5.0.1:

`Uncaught ScssPhp\ScssPhp\Exception\CompilerException: $n: 252.6 is not an integer.: vendor/twbs/bootstrap/scss/_functions.scss on line 140, at column 5 Call Stack: #0 function luminance vendor/twbs/bootstrap/scss/_functions.scss on line 123 #1 function contrast-ratio vendor/twbs/bootstrap/scss/_functions.scss on line 108 #2 function color-contrast vendor/twbs/bootstrap/scss/_functions.scss on line 156 #3 import vendor/twbs/bootstrap/scss/_buttons.scss bootstrap.scss on line 19
`

Version 1.4.1 had no issues. I'm not really sure what else I can add to this, but if you require more information then please let me know.

**Comment by malberts** [comment]
I'm adding to this issue because I also have a Bootstrap-related issue when moving from scssphp 1.4.1 to 1.5.0.
However, it is not exactly the same because I'm using Bootstrap 4.6 and jumping through a few more hoops (MediaWiki + [SCSS library](https://github.com/ProfessionalWiki/scss) + [Bootstrap extension](https://github.com/ProfessionalWiki/Bootstrap) + [Chameleon skin](https://github.com/ProfessionalWiki/chameleon)).

The error message also isn't the same, but in both cases it looks like there's an integer vs float issue.

This is my error:
```
/* SCSS compile error: $n: List index may not be 0.: extensions/Bootstrap/resources/bootstrap/scss/mixins/_box-shadow.scss on line 13, at column 9
Call Stack:
#0 mixin box-shadow extensions/Bootstrap/resources/bootstrap/scss/_custom-forms.scss on line 36
#1 import extensions/Bootstrap/resources/bootstrap/scss/_custom-forms.scss (unknown file) on line 1*/
```
And a reference to my original report in the MediaWiki Bootstrap repo: https://github.com/ProfessionalWiki/Bootstrap/issues/49

**Comment by leonardfischer** [comment]
+1 having the same issue as @axllent
