### ISSUE TITLE
v1.5.1 fails to compile Bootstrap 4.6.0

### ISSUE THREAD

**Issue by malberts** [scssphp/scssphp#403]
I looks like my issue with Bootstrap 4.6 is unrelated to the Bootstrap 5 issue (https://github.com/scssphp/scssphp/issues/397#issuecomment-841632120).

I updated to v1.5.1 and I'm still getting this error:
```
/* SCSS compile error: $n: List index may not be 0.: extensions/Bootstrap/resources/bootstrap/scss/mixins/_box-shadow.scss on line 13, at column 9
Call Stack:
#0 mixin box-shadow extensions/Bootstrap/resources/bootstrap/scss/_custom-forms.scss on line 36
#1 import extensions/Bootstrap/resources/bootstrap/scss/_custom-forms.scss (unknown file) on line 1*/
```

**Comment by malberts** [comment]
For what it's worth, here's the scss for the "nth" issue being referred to in the stacktrace:
https://github.com/twbs/bootstrap/blob/v4.6.0/scss/mixins/_box-shadow.scss#L12
https://github.com/twbs/bootstrap/blob/v4.6.0/scss/_custom-forms.scss#L36

**Comment by stof** [comment]
Can you share the code you are compiling ? Bootstrap 4.6 was used by our CI for 1.5.0, so it is definitely not the default compilation of Bootstrap that fails.

**Comment by malberts** [comment]
I think I found the issue. It seems to be related to this:
`$enable-shadows: true`
When I set that to `false` it compiles.

That settings is disabled by default in BS 4.6: https://getbootstrap.com/docs/4.6/utilities/shadows/
So if your CI runs unmodified BS 4.6 then it probably wouldn't have that issue.

**Comment by stof** [comment]
OK, looking at the issue, I would say that scssphp 1.4.x was already not producing the right behavior there (but it was silently doing a bad thing instead of reporting an error). The issue is that it considers that `length($shadow)` is 0, while it should be `1` when passing `null`. Previously, as `nth` was considering that the index `0` of a list is the same than the index `1`, it was hiding the issue.

**Comment by stof** [comment]
Reduced test case for the root cause of the issue:

```scss
$list: (null);

a {
    b: length($list);
}
```

dart-sass produces `1` as output, while scssphp produces 0.

**Comment by GrupoWebex** [comment]
My error result. Working on 1.4.1

> Fatal error: Uncaught exception 'ScssPhp\ScssPhp\Exception\SassScriptException' with message '$n: List index may not be 0.' in **********vendor/scssphp/scssphp/src/Exception/SassScriptException.php:30
Stack trace:
#0 **********vendor/scssphp/scssphp/src/Compiler.php(8583): ScssPhp\ScssPhp\Exception\SassScriptException::forArgument('List index may ...', 'n')
#1 [internal function]: ScssPhp\ScssPhp\Compiler->libNth(Array, Array)
#2 **********vendor/scssphp/scssphp/src/Compiler.php(6151): call_user_func(Array, Array, Array)
#3 **********vendor/scssphp/scssphp/src/Compiler.php(3647): ScssPhp\ScssPhp\Compiler->callNativeFunction('nth', Array, Array, Array)
#4 **********vendor/scssphp/scssphp/src/Compiler.php(3573): ScssPhp\ScssPhp\Compiler->fncall('nth', Array)
#5 **********vendor/scssphp/scssphp/src/Compiler.php(7615): ScssPhp\ScssPhp\Compiler->reduce(Array, true)
#6 [internal function]: ScssPhp\ in **********themes/default/views/layouts/admin/default_css.twig on line 5

**Comment by stof** [comment]
@GrupoWebex how are you getting an uncaught SassScriptException ? SassScriptException is expected to always be caught by the Compiler itself, to be wrapped in a exception implementing SassException. Based on the stack trace, I suspect that you might be calling the compiler internal methods instead of using the public API.

Anyway, I've identified the root cause of this issue. Now, I need to work on the fix (which probably involves finishing the work I started last week and gave up about reimplementing the handling of lists in the library, by going down to the end of the rabbit hole it became)
