### ISSUE TITLE
Error $amount: Expected 75% to be within 0% and 1%`.

### ISSUE THREAD

**Issue by mahagr** [scssphp/scssphp#475]
If I use the following code in v1.7.0:

```scss
$base-border-color: #e7e8ea !default;
$base-color: fadeout($base-border-color, 75%);
```

I get an error:

`Oops, CSS Compilation on file 'file.scss' failed on error: $amount: Expected 75% to be within 0% and 1%`

Before the percentages worked just fine.

**Comment by stof** [comment]
First, the standard name for the function is `fade-out`, not `fadeout` (the `fadeout` name works in scssphp due to the internal implementation of built-in functions in our compiler and the fact that PHP method names are case-insensitive). Using `fadeout` in dart-sass would consider it as a CSS function and render `fadeout(#e7e8ea, 75%)` in the CSS.

And passing a percentage to `fade-out` is not supported by official Sass implements. It expects to have a number between 0 and 1 (generally unitless, but dart-sass does not enforce the absence of unit). Running dart-sass on the following output produces an error:

```scss
$base-border-color: #e7e8ea !default;
$base-color: fade-out($base-border-color, 75%);

a {
    b: $base-color;
}
```

```
Error: $amount: Expected 75% to be within 0% and 1%.
  ╷
2 │ $base-color: fade-out($base-border-color, 75%);
  │              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  debug.scss 2:14  root stylesheet
```

**Comment by mahagr** [comment]
Thank you for the comment, you're right, it seems to be badly written SCSS.
