### ISSUE TITLE
Compiler::getSourcePosition() deprecated

### ISSUE THREAD

**Issue by ryssbowh** [scssphp/scssphp#541]
Hi,

I see Compiler::getSourcePosition() has been deprecated in f37344933a025b439b2b892124d392de59d6ad37, is there another way of accessing the currently compiled file and line number ?

Thank you

**Comment by stof** [comment]
What is your use case for that ?

**Comment by ryssbowh** [comment]
I register a custom url function on the compiler which extracts the assets from the scss. 
The currently compiled file is then needed to resolve the relative assets paths.
Line number is useful to warn the user about assets that can't be found.

**Comment by stof** [comment]
The issue with this method is that the planned refactoring for scssphp 2 won't allow to keep it (the Compiler class itself won't be tracking that state anymore).

To report errors, the solution is to throw a SassScriptException without including the location where the error happens. Then, scssphp will add the location when converting it to the final SassException.
For the override of the `url()` function to resolve relative paths, I don't have a clean solution for now, because overriding the `url()` function for that is a hack (and a fragile one, as not all `url()` are parsed as function calls, as the syntax of the CSS `url()` function is special). In the official Sass implementations, `url` is even a reserved name that cannot be redefined, due to this special parsing needs. And scssphp 2 might apply the same restriction (that's not sure yet, it will depend whether we can avoid applying it while becoming fully spec compliant for the parsing)
