### ISSUE TITLE
PHP 8 crash

### ISSUE THREAD

**Issue by stempora** [scssphp/scssphp#573]
Hello,

Latest version when compiling it dies on php 8.1 ( was working fine 2 days ago on php 7.4 ) 

ScssPHP Version: 1.10.2

Fatal Error : Attempt to assign property "selectors" on null
/vendor/scssphp/scssphp/src/Compiler.php
Line: 1935

**Comment by stof** [comment]
without a reproducing case and a stack trace, there is not much I can do to help.

Btw, looking at the code, there is an assertion about getting a non-null value just before that assignment. So it looks like this invariant might be wrong in some case (which is why we need a reproducing case, as nothing in our testsuite failed there). Turning on PHP assertions in your PHP setup would give you an AssertionError instead of that Fatal Error, which might make it easier for you to get a stack trace (even though fatal errors also generate a stack trace). And they might indicate another failed invariant earlier.

**Comment by stempora** [comment]
Using "contenxt in context" crashes it. Before was working fine.

`@mixin context($old-context, $new-context) {
	$parent : &;

	@at-root #{selector-replace($parent, $old-context, $new-context)} {
		@content;
	}
}



.select2-selection--single{
	.select2-selection__rendered {
		@include context(
			".select2-container",
			".select2-container.select2-container--default"
		) {
			color: red;
			@include context(
				".select2-container--default",
				".select2-container--default.select2-container--open"
			) {
				color: white;
			}
			
		}
	}

}
`

**Comment by stof** [comment]
@stempora I found the fix for that. But what I don't understand is how this could have worked on PHP 7.4 (unless you were not using the same scssphp version there, without telling it in the report, in which case the PHP version change would not be the relevant change to explain the difference).

**Comment by stempora** [comment]
Hi,

I use this on our cms and it works fine ( same php code , same sass code, what i gave you its only a part of it ) on php 7.4 yesterday when i upgraded certain domains to 8.1 stopped working while the others that are still on 7.4 works fine. Nothing changed.

**Comment by stof** [comment]
ah, I see. On PHP 7.4, you only get a warning (`Warning: Creating default object from empty value in /app/src/Compiler.php on line 1935`), and by luck, this empty object with just this property does not break other things in the compilation.

**Comment by stempora** [comment]
I see, i didnt notice that as i have the warning disabled in production. Thanks a lot for the help!

**Comment by stof** [comment]
@stempora this is now released as 1.10.3

**Comment by stempora** [comment]
Thank you, i noticed 15 mins ago when i updated composer :)
