### ISSUE TITLE
PROBLEM with a name of a function 

### ISSUE THREAD

**Issue by AlexisSavreuxLecoeur** [scssphp/scssphp#583]
The function name in src\dependencies\PHP_SCSS\src\Parser.php is already used in PHP 8. It generate lots of error in my VS CODE with Intellisense extension.

**Comment by stof** [comment]
Why function name are you talking about ?

**Comment by AlexisSavreuxLecoeur** [comment]
/**
     * Try to match something on head of buffer
     *
     * @param string $regex
     * @param array  $out
     * @param bool   $eatWhitespace
     *
     * @return bool
     *
     * @phpstan-impure
     */
    protected function match($regex, &$out, $eatWhitespace = null)
    {
        $r = '/' . $regex . '/' . $this->patternModifiers;

        if (! preg_match($r, $this->buffer, $out, 0, $this->count)) {
            return false;
        }

        $this->count += \strlen($out[0]);

        if (! isset($eatWhitespace)) {
            $eatWhitespace = $this->eatWhiteDefault;
        }

        if ($eatWhitespace) {
            $this->whitespace();
        }

        return true;
    }

on line 1493

**Comment by AlexisSavreuxLecoeur** [comment]
I have also this error when I use @use in SCSS which is recommanded now. 
![image](https://user-images.githubusercontent.com/77328837/173191136-129e3801-8c1e-4408-ae85-0c22ce9de756.png)

**Comment by AlexisSavreuxLecoeur** [comment]
We don't use :root rulles in SCSS with your dependencies

**Comment by stof** [comment]
`match` is not an issue on PHP 8 because keywords are contextual on PHP 8+ and so such a method name is allowed. If the VS Code Intellisense extension reports it as a bug, then the bug is in this extension instead.

Regarding `@use`, Sass modules are not implemented yet in scssphp. This is tracked in #55.
And for `calc`, you need to use interpolation to use Sass variables. Support for first-class calc (which is a new feature in Sass, implemented only in dart-sass 1.41+). This is tracked in #463.
