### ISSUE TITLE
Compile Issue within content in CSS

### ISSUE THREAD

**Issue by kroero** [scssphp/scssphp#627]
Hi,
I'm using scssphp 1.11.0 and have the problem that font awesome icons not showing up.
in the output file the content looks for example like : `content: "ï„‡";` instead of `content: "\f107"`;

I found out that this is not only an issue with fontawesom.
I have the problem when i only want to compile a simple css.
for example:

```scss
.text{
    content: "\f107";
}
```

Source Code:

```php
<?php
require_once "assets/scssphp-1.11.0/scss.inc.php";

use ScssPhp\ScssPhp\Compiler;

try {

    $compiler = new Compiler();
    echo $compiler->compileString('.text{ content: "\f107"; }')->getCss();

} catch (\Exception $e) {

    echo '';
    syslog(LOG_ERR, 'scssphp: Unable to compile content');
}

?>
```

can you please tell me how I can fix this?

best regards,
Roman

**Comment by stof** [comment]
For me, the output of this code snippet looks like this:

```css
@charset "UTF-8";
.text {
  content: "";
}
```

And this is perfectly valid CSS. It renders the Unicode character U+F107 instead of a CSS escape sequence `\f107`, but that's strictly equivalent (as this escape sequence represents exactly that unicode character). So this does not reproduce a bug to me.

**Comment by kroero** [comment]
Hello and thank you for your help!
I was able to fix the coding using a .user.ini file, however the icons are still not displayed.
The server wants the value "\f107" in the rendered CSS file in the content for example, so that the icon is displayed?
Do you have a tip for me what the problem could be? On another webserver it works if the CSS file contains the Unicode character U+F107.
Thank you and best regards,
Roman

**Comment by stof** [comment]
Make sure you serve the CSS file as UTF-8, or that you don't remove the charset hint from the CSS file (`@charset "UTF-8";` in expanded mode or the UTF-8 BOM in compressed mode)

**Comment by kroero** [comment]
hi. the file should be ok.
https://din-notlicht.com/wp-content/themes/notlicht-theme/styletest.php/styletest.scss?v=16661587752
but the server don't render it

**Comment by stof** [comment]
Your servers sends no content-type header at all (and so does not include the charset in it). and your generated CSS seems to inject more comments before the `@charset`. But `@charset` is ignored in CSS if it is not the first thing in the file (because the file needs to be converted from its charset to UTF-8 _before_ starting the parsing so this is not supported later in the file).
