### ISSUE TITLE
Missing documentation: $path variable in compileString($scssCode, $path = null) function

### ISSUE THREAD

**Issue by kossahl** [scssphp/scssphp#635]
Being new to scssphp I'm trying to find a way to compile multiple sass folders with multiple sass entry files into one single css file.
While looking for a solution to this I was wondering about the `$path` variable in the `compileString($scssCode, $path = null)`.

What exactly is this variable used for and when should it be set?

**Comment by stof** [comment]
This is expected to be the path of the entrypoint file (where the scssCode comes from), which allows to resolve relative imports. Passing null will disable relative imports (and if you don't configure some import paths, it means there is nothing left to resolve `@import`)

**Comment by Halopend** [comment]
@stof Feel I'm doing something wrong and wanted to check. Used to use the compile method from the compiler, but have been transitioning to compile string. I'm getting an error I did not before, but I refactored pretty hard so it's hard to source.

https://gist.github.com/Halopend/5224cbcaf0c4ad7e55d723876be5a6e4

Any Help would greatly appreciated. I added debugger information inline right around where I use self::$SCSS_COMPILER->compileString($scssIn, $scss_dir) so you can see the state of the variables directly.

It's not been clear to me if import handling is considered our job in using the library or if it's the plugins responsibility, but the imports seem to work (possibly because I'm not honouring the full spec with relative imports etc.)

Anyway, source-mapping is saying stdin now when it wasn't before so I'm not sure where I've gone off.

To properly disambiguate.... what the role of compiler->setImportPaths vs supplying the path to compiler->compileString(...., $path)?

Is it just a per-file override?  Things are compiling properly as changes to partials get reflected in the compiled css,  even though I don't supply partials at anypoint to compile. Makes me think there is some redundancy in the required vars we have to supply (your parser knows the files exist and reads them, why set them explicitly in the compileString method) but maybe there is some part of the spec I'm missing or customization possibilities you are covering I'm not seeing (split folders where the concept of a single root folder falls apart).

Hopefully that's clear.

**Comment by stof** [comment]
Side note: for the `setOutputStyle` call, you should rather use the `OutputStyle` constant rather than hardcoding the string.

**Comment by stof** [comment]
I added some explanations in the phpdoc in #684
