### ISSUE TITLE
CSS source map is generated from compiled version

### ISSUE THREAD

**Issue by maki3000** [scssphp/scssphp#660]
I try to generate a CSS source map with:

```php
$theme = Theme::getActiveTheme(); // some CMS related code to get the right path
$theme_path = $theme->getPath();

$sc = new Compiler();
$sc->setSourceMap(Compiler::SOURCE_MAP_FILE);
$sc->setSourceMapOptions([
    'sourceMapBasepath' => '',
    'sourceRoot' => '/',
    'sourceMapWriteTo' => $theme_path . '/assets/css/',
]);

foreach ($cacheInfo['files'] as $file) {
    $cssFilePath = $theme_path . '/' . $file;

    if (file_exists($cssFilePath)) {
        $cssContent = file_get_contents($theme_path . '/' . $file);
                        
        $result = $sc->compileString($cssContent, $cssFilePath);

        $encodedJsonSourceMap = json_encode(json_decode($result->getSourceMap()));
        $base64DataSourceMap = base64_encode($encodedJsonSourceMap);
        $dataUriSourceMap = 'data:application/json;base64,' . $base64DataSourceMap;
                        
        $contents .= "\n /*# sourceMappingURL=" . $dataUriSourceMap . " */";
    }
}
```

It all works, but the map is defining the compiled CSS and not the original.

What do I do wrong here?

**Comment by stof** [comment]
Can you provide a standalone reproducing case ? Your code snippet depends on some other code so I cannot use it as a reproducer.

**Comment by stof** [comment]
btw, if you want to use inline sourcemaps in the comment at the end of the CSS, you could configure the compiler to do it for you with `Compiler::SOURCE_MAP_INLINE`

**Comment by maki3000** [comment]
I'm trying to write a standalone case in phpsandbox:
https://phpsandbox.io/n/scssphp-css-source-map02-ud39k#index.php

The thing is, that I don't know how to decode the mappings. For sure there's something wrong, because the line number is always 0.

I found a LESS decoder (I know, I'm providing SCSS) here:
https://github.com/wUFr/LetItSnow/blob/master/lessphp/SourceMap/Base64VLQ.php

**Comment by stof** [comment]
When I'm taking the CSS and sourcemap generated by the compiler and saving it on disk and I add it in an HTML page, the browser dev tools properly show me that the styles for `body` come from line 7 and the styles for `*, ::before, ::after` come from line 24. So the sourcemap is working totally fine.
To me, the issue is in the way you decode the mapping, not in scssphp.

note that I'm not even sure the lessphp code you are referencing (which is not from the official lessphp repo) is correct. Our own Base64VLQ decoding logic is different, and I don't think either of the 2 is battle-tested given that both lessphp and scssphp care about generating a sourcemap, not about decoding it (for instance, the decoding code in scssphp is totally unused and untested).

**Comment by maki3000** [comment]
I'm definitely doing something wrong in my CMS. When I add the generated source map manually, it also displays the correct line numbers.

Thank you very much for your help!
