### ISSUE TITLE
Substituting in :root does not work

### ISSUE THREAD

**Issue by clausharup** [scssphp/scssphp#672]
:root {
    --width-breakpoint: $breakPointWidth;
}

**Comment by stof** [comment]
The issue is not `:root` at all.

What does not work is substituting variables in custom properties. And this is not a bug at all but a feature (because `$breakPointWidth` is a valid content for a custom property in CSS as well). To use a Sass variable in the value of a custom property, you must use interpolation: https://sass-lang.com/documentation/style-rules/declarations/#custom-properties

**Comment by clausharup** [comment]
Having this: scss:

:root {
--width-breakpoint: $breakPointWidth;
}

body {
  main {
    max-width: var(--width-breakpoint);
    width: $breakPointWidth;
  }
}

Gives me this css:
:root {
--width-breakpoint: $breakPointWidth;
}

body main {
    max-width: var(--width-breakpoint);
    width: 1200px;
}

**Comment by stof** [comment]
The answer is in my previous comment: this is the expected behavior of the Sass language. If you want to substitute a Sass variable in a custom property, using interpolation is required.

**Comment by clausharup** [comment]
Thx :-)
