### ISSUE TITLE
How to get version of project inside code

### ISSUE THREAD

**Issue by janstieler** [scssphp/scssphp#697]
Hi,
how can I see the library version inside the code?
Normally its decalared inside the composer.json of the project but not by scssphp.
It wouldbe nice because in my project composer.json is 1.12.0 decalred but composer is not updating the libary so I hav eto proof which version now is installed.

Best

**Comment by kodie** [comment]
@janstieler Check the value of the `VERSION` constant inside of `ScssPhp\ScssPhp\Version` (`vendor/scssphp/scssphp/src/Version.php`)

**Comment by stof** [comment]
Almost no project define the version in the composer.json because this only causes issues with composer for projects managed in a VCS repository: composer always takes the version from git. An explicit version in composer.json can only make composer mark that version as broken and reject it, but will never provide any benefit. This means it is a net negative for maintainers.

The way to know which version is installed is to ask composer:
- for devs, use `composer show` to see the info about the installed packages (you can also use `composer show --locked` to see the info about the locked version, in case your vendor folder is not in sync with the lock file)
- to check it from the code, use the Composer runtime API: https://getcomposer.org/doc/07-runtime.md

For scssphp specifically, we have the `ScssPhp\ScssPhp\Version` class holding a constant with the version. But be careful that this is updated manually when doing a release, and in the past, it already happened that this was forgotten. And in version 2 of scssphp where composer will be the only officially supported way of installing the library, I plan to drop that class to remove that manual update. Projects using composer should use the composer runtime API to get the info.

**Comment by janstieler** [comment]
Hi,
thanks for the answers. `composer show`works perfect.
To set the version inside composer.json I know it from Kirby CMS for there plugin.
So I thought it is a normal way to set the package version number.

Best
