### ISSUE TITLE
Ability to register custom mixins?

### ISSUE THREAD

**Issue by kodie** [scssphp/scssphp#698]
The `scssphp-glob` function throws the following error:

```
The "scssphp-glob" function is deprecated an will be removed in ScssPhp 2.0. Register your own alternative through "Compiler::registerFunction
```

however this doesn't seem to be possible with `registerFunction` as that function is expected to return a value for a property.

I think what we actually need is a `registerMixin` function so that we could do something like this:

```
@include glob-import('../component/*/*.scss');
```

Unless I'm missing something?

**Comment by stof** [comment]
`scssphp-glob` was not a mixin either. Its usable with not with `@include` but with `@import` (however, thinking about that, returning a list of files to import for an expression instead of reporting a single one is probably also a non-standard feature).

Regarding the ability to register custom mixins, this is unlikely to happen. By definition, a mixin produces a side effect in the compilation. And I don't see how this could be done without access to the internal state of the compiler.
Looking at dart-sass, the only built-in module that contains some mixins (rather than only functions or immutable variables) is `sass:meta` which is (by design) a privileged module having access to the internals. dart-sass does not allow either registering custom mixins provided by the host. Their compiler API only allows custom functions (our own API allows registering custom variables, for which I will need to make sure we define a well-behaving semantic once we implement modules)

**Comment by stof** [comment]
To clarify my previous comment: such `glob` importer will definitely not be part of scssphp itself. But if this approach work (I haven't tested if my idea actually works), it will be something that can be shipped as a separate package.
