### ISSUE TITLE
SCSS class not found when i call to the function

### ISSUE THREAD

**Issue by neerajs0532** [scssphp/scssphp#712]
SCSS class not found.
Fatal error: Uncaught Error: Call to undefined function compile_scss_to_css() in /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-content/plugins/custom-scss-compiler/custom-scss-compiler.php:51 Stack trace: #0 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-settings.php(473): include_once() #1 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-config.php(103): require_once('/Users/a1d8sihz...') #2 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-load.php(50): require_once('/Users/a1d8sihz...') #3 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-blog-header.php(13): require_once('/Users/a1d8sihz...') #4 /Users/a1d8sihz/Local Sites/scsscompiler/app/public/index.php(17): require('/Users/a1d8sihz...') #5 {main} thrown in /Users/a1d8sihz/Local Sites/scsscompiler/app/public/wp-content/plugins/custom-scss-compiler/custom-scss-compiler.php on line 51
There has been a critical error on this website.

[Learn more about troubleshooting WordPress.](https://wordpress.org/documentation/article/faq-troubleshooting/)

**Comment by zoglo** [comment]
@neerajs0532
This seems to be an issue with the "custom-scss-compiler" plugin in WordPress and is unrelated to scssphp.
You should contact the plugin developer.

**Comment by neerajs0532** [comment]
> @neerajs0532 This seems to be an issue with the "custom-scss-compiler" plugin in WordPress and is unrelated to scssphp. You should contact the plugin developer.

how can i contact to the plugin developer. can u help me in contacting to plugin developer

**Comment by zoglo** [comment]
This is scssphp, not Wordpress nor any wordpress plugin.
You should check the theme you are using and contact the theme-provider yourself.

**Comment by stof** [comment]
Scssphp does not define any `compile_scss_to_css` function (and it is not expected to define one). Getting an error because this function does not exist is definitely not an error in scssphp itself.

And the stack trace of the error points to file in `.../wp-content/plugins/custom-scss-compiler/custom-scss-compiler.php`, so this looks like the error is in a wordpress plugin named `custom-scss-compiler`. But this github repository is not about this wordpress plugin (it is not even about wordpress at all).
