### ISSUE TITLE
[suggestion] remove Exception class

### ISSUE THREAD

**Issue by nenge123** [scssphp/scssphp#750]
all of Exception class is empty and nothing else
====

- use `Exception code number` replace the `SassScriptException` `SassException` `RangeException` `ParserException` `CompilerException`
> like 1XXX is `SassScriptException`   
> X1XX is `ValueError` , X2XX `FunctionError`  X3XX `ParserError`

- `sprintf('Duplicate named argument $%s.',$arg)` change to  like about `ScssError::duplicate_argument->sprintf($arg)`
```php
        enum ScssError:string
        {
            case duplicate_argument = 'Duplicate named argument $%s.';
            case ARG_POS_NAME = 'Argument $%s was passed both by position and by name.';
            public function sprintf($arg)
            {
                return sprintf($this->value,$arg);
            }
            public function Exception($arg,int $code = )
            {
                throw new \Exception($this->sprintf($arg),$code);
            }
        }
```

`SassScriptException::forArgument` change to `ScssPhp\ScssPhp\Compiler::forArgument`
```php
    public static function forArgument($message, $name = null)
    {
        $varDisplay = !\is_null($name) ? "\${$name}: " : '';

        return new \Exception($varDisplay . $message);
    }
```

**Comment by stof** [comment]
This is a no-go because our exception classes have separate meaning.

Compilation failures will be reported by throwing an exception implementing SassException (allowing `catch (SassException $e)` to work if you want to catch only sass compilation failures and not other errors in your PHP program). Note that all classes that implement this interface are tagged as `@internal` meaning that projects should not catch those subtypes directly (however, our own logic has good reason to use separate classes).

`SassScriptException` represents errors reported during the execution of SassScript expressions. Those are caught by the compiler itself (and so we definitely want to be able to do `catch(SassScriptException $e)` instead of catching all PHP exceptions and hoping that we can identify which one should actually be caught).

This suggestion would make the code a lot worse than today and harder to maintain (and would be a BC break)
