### ISSUE TITLE
[Feature Request] Retrieve all variables marked as `!default`

### ISSUE THREAD

**Issue by fabian-mcfly** [scssphp/scssphp#780]
Hi and thanks for your 2.0 release!

I was using your library not only to compile SCSS to CSS, but also to retrieve all variables in the parsed files (including the imported ones) by extending the `Compiler`-class.
This gave me an easy way to access all customizable variables and give users a chance to change those.

Sadly, this class now is not only final but also most things have changed.
I haven't had much time to look into the rewrite so I am not that familiar with how everything works together.

Could you provide a way to keep track of - and retrieve - all variables defined in all used files?

I am currently using this approach but that only gives the variables defined in the same file, not in imported ones (the Parser is easier to use than the other ways I've tried):

```php
$parser = new ScssParser(file_get_contents($scssFile));
$stylesheet = $parser->parse();
$vars = [];

foreach ($stylesheet->getChildren() as $var) {
  if (!is_a($var, VariableDeclaration::class)) {
	  continue;
  }
  
  if (!$var->isGuarded()) {
	  continue;
  }
  
  $vars[ $var->getName() ] = $var->getExpression();
}
```

If you don't see any benefit for your library (and I can see why you wouldn't): what is the easiest way to traverse all imports without rewriting the `EvaluateVisitor`- and/or `ImportCache`-classes?

**Comment by stof** [comment]
You could use a (custom) visitor to run some logic on each DynamicImport, using the ImportCache to resolve the import and then visiting the imported stylesheet again. This visitor could inspire from the `StatementSearchVisitor` for the way to visit child nodes (except you don't want to stop visiting nodes when finding the searched statement, as done in that visitor).

However, note that none of those APIs (including the parser that you use in your snippet) are covered by our backward compatibility promise (following semver) as they are all tagged as `@internal`. So they might break when upgrading the library (in particular, new methods will be added in the visitor interface when adding new types of nodes). If you do this, I strongly suggest you to write extensive tests for this, that you can run when upgrading the library.

I don't know why you want to collect those top-level variables, but note that a guarded variable in an imported file might not be customizable from the entrypoint. It is customizable only if the same variable is not yet defined before the import. This means that once you start visiting imports, you also need to track unguarded variable declarations (and the order of variable declarations and imports).

Side note; I suggest you to use the static method `Stylesheet::parse` instead of managing the parser yourselves. It will be less confusing once you start parsing multiple stylesheets as the parser instance is not reusable (as it stores the source code inside it).

**Comment by fabian-mcfly** [comment]
Thanks for your reply!

The reason I am reading variables is because users are able to change colors, some font-sizes and line-heights, and it should be enough to define those variables in the SCSS files. Otherwise (for example setting them in SCSS files and in a PHP config file), the SCSS file (and the resulting CSS file) might not match the PHP config file (violating Single Point of Truth [SPOT]).

I have your repo on my watchlist, so I see all the changes and I have tests for it, thanks!
Maybe, for another major version, the parser could be a standalone package?!

**Comment by stof** [comment]
Given that this repo is now a port of dart-sass (to be easier to maintain to keep it in sync with the changes in Sass), I don't want to split part of it in a separate package. It would make maintenance very painful, by forcing to maintain backward compatibility on those APIs, instead of being able to keep them in sync with dart-sass.

My recommendation is to define all your configurable variables in the entrypoint file (meaning you don't need to parse imports at all, and your code snippet in the opening issue works). This is what you will need to do anyway once you migrate to Sass modules (which I hope to implement soon in scssphp, especially given imports are now deprecated in favor of modules in dart-sass).
