### ISSUE TITLE
Variables are ignored

### ISSUE THREAD

**Issue by deadlyw1re** [scssphp/scssphp#91]
When you use root property declarations like `--primary` the variable after it gets ignored.

Input:
```
use ScssPhp\ScssPhp\Compiler;
-
$scss = new Compiler();
$scss->setVariables(array(
    'primary' => '#000000',
));

echo $scss->compile(':root { --primary: $primary }');
```

Output:
```
:root { --primary: $primary }
```

When changing `--primary` to something like `color:` it works, output will be:
```
:root { color: #000000 }
```

**Comment by robocoder** [comment]
As I mentioned in #90, this doesn't work in dart-sass, ruby sass, libsass, etc.

Please use sassmeister.com to test your example:
```
$primary: #000000;
:root { --primary: $primary }
```

**Comment by halfpastfouram** [comment]
@robocoder The example you provided does not work on sassmeister.com:

![Screenshot 2020-04-02 09 40 22](https://user-images.githubusercontent.com/3202331/78222797-1bfaf680-74c6-11ea-9706-554115cfc9f5.png)

You say it doesn't work in dart-sass, ruby sass, libsass etc. Why doesn't this work? And does this mean it is out of your hands and you cannot provide a solution for this?

What stuns me is that this feature has worked in these past without any trouble. I've just tested with the following versions and they all work flawlessly:
- v1.0.0
- v1.0.1
- v1.0.2
- v1.0.3
- v1.0.4
- v1.0.5
- v1.0.6
- v1.0.6
- v1.0.7

It seems that this stopped working since v1.0.8

Please reopen this issue. Let's see if we can tackle this problem.

**Comment by Cerdic** [comment]
@halfpastfouram 
the working syntax is
```
$primary: #000000;
:root { --primary: #{$primary} }
```

You can check this on Sassmeister.

The fact is the purpose of this ScssPHP is to stick as close as possible to the sass-lang specification, and we are trying to reduce the gap witth dart-saas and improving the specification compliance.

So you should consider that the fact the erroneous syntax worked in previous versions was a bug and a non-compliance, and we should not come back on this

**Comment by halfpastfouram** [comment]
Fair point. Thank you for your helpful comment.

Seeing as there is no mention of this in the docs (https://scssphp.github.io/scssphp/docs/) it would be great to add some information about this behavior/requirement:

> Interpolation is required when using root property declarations:
> ```
> require_once "scssphp/scss.inc.php";
> 
> use ScssPhp\ScssPhp\Compiler;
> 
> $scss = new Compiler();
> 
> echo $scss->compile('
>   $color: #abc;
>   root { --color: #{$color} }
> ');
> ```
> 
> For more information about interpolation see [sass-lang.com](https://sass-lang.com/documentation/style-rules/declarations#interpolation)
